# Prints a confirmation whenever a player is given a loadout
verbose: true
# Prints debug messages
debug: false
# Adds a ms delay if needed for plugin compatibility
delay: 0

# This sets up the loadouts and the permission nodes required to get them
# For instance "customloadouts.donatorloadouts" gives all loadouts under the donatorloadouts node below, as long as the class and chance checks are successful.
customloadouts:
    # Name of this permission node
    donatorloadouts:
        # Class, check #resources in the SMOD discord server for class names, set to all to give to all classes
        all:
            # Percentage chance for item group to spawn
            - 50:
                # Items to spawn, check #resources in the SMOD discord server for item names.
                # You can start a loadout with REMOVEITEMS and REMOVEAMMO to delete the existing items/ammo.
                # All weapons spawn with one mag/clip loaded which cannot be removed, giving ammo adds the ammo directly to the player instead of spawning it as an item in their inventory.
                - COIN # This example has a 50% chance to spawn a coin to all players with the customloadouts.donatorloadouts permission node
            - 10:
                - MEDKIT
        SCIENTIST:
            - 10:
                # Starts with REMOOVEITEMS to clear the default inventory before the items are added.
                - REMOVEITEMS
                - MAJOR_SCIENTIST_KEYCARD
                - MEDKIT
            - 5:
                - REMOVEITEMS
                - REMOVEAMMO
                - USP
                - DROPPED_9
                - DROPPED_9
                - MAJOR_SCIENTIST_KEYCARD
                - MEDKIT
        NTF_CADET:
            - 20:
                - MAX: 1
                - COOLDOWN: 30
                - MEDKIT
                - MEDKIT
            - 10:
                - MAX: 1
                - COOLDOWN: 30
                - REMOVEITEMS
                - NTF_LIEUTENANT_KEYCARD
                - P90
                - RADIO
                - MEDKIT
                - DISARMER
    moderatorloadouts:
        CLASSD:
            - 30:
                - FLASHLIGHT
    adminloadouts:
        all:
            - 100:
                - MICROHID
                - MICROHID
                - MICROHID
                - MICROHID
                - MICROHID
                - MICROHID
                - MICROHID
                - MICROHID